version: '3'

services:

  #dspfront:
  #  image: dspfront
  #  container_name: dsp_dev_dspfront
  #  volumes:
  #    - ./../.env:/dspfront/.env
  #  ports:
  #    - 5001:5001
  #  restart: unless-stopped

  nginx:
    image: nginx:1.17.10
    container_name: iguide_nginx
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - api

  api:
    image: iguide_api
    container_name: iguide_api
    volumes:
      - ./:/app
      #- ./tests:/tests
    #entrypoint: bash dev-entrypoint.sh
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
